export const CATEGORIES = [
    'Tech', 'Health', 'AI', 'Education', 'Finance',
    'E-commerce', 'Entertainment', 'Social Impact', 'Sustainability', 'Other',
  ]
  
  export const CATEGORY_STYLES = {
    Tech          : 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
    Health        : 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
    AI            : 'bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-400',
    Education     : 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400',
    Finance       : 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
    'E-commerce'  : 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400',
    Entertainment : 'bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-400',
    'Social Impact': 'bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-400',
    Sustainability : 'bg-lime-100 text-lime-700 dark:bg-lime-900/30 dark:text-lime-400',
    Other         : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
  }
  
  export const MOCK_USER = {
    displayName: 'Alex Johnson',
    email      : 'alex@example.com',
    photoURL   : null,
  }
  
  export const MOCK_IDEAS = [
    {
      _id             : '1',
      title           : 'AI-Powered Mental Health Companion',
      shortDescription: 'A conversational AI providing 24/7 emotional support and personalized wellness tracking for modern professionals.',
      detailedDescription: 'The platform uses advanced NLP models to engage users in empathetic conversations, track mood patterns over time, and suggest evidence-based coping strategies. Unlike traditional therapy apps, it proactively reaches out when it detects behavioral changes.',
      category        : 'Health',
      tags            : ['AI', 'Mental Health', 'Wellness'],
      imageURL        : '',
      authorName      : 'Sarah Chen',
      authorPhoto     : '',
      authorEmail     : 'sarah@example.com',
      commentCount    : 24,
      bookmarkCount   : 12,
      estimatedBudget : '$80,000',
      targetAudience  : 'Working professionals aged 25–45 experiencing burnout and anxiety.',
      problemStatement: 'Mental health support is prohibitively expensive and hard to access. Therapy waitlists can stretch months and sessions cost $150+ per hour.',
      proposedSolution: 'A subscription-based AI companion that learns from each conversation, delivers personalized daily check-ins, and escalates to human therapists when needed.',
      createdAt       : '2024-01-15T10:00:00Z',
      updatedAt       : '2024-01-15T10:00:00Z',
    },
    {
      _id             : '2',
      title           : 'Blockchain-Based Supply Chain Tracker',
      shortDescription: 'A transparent blockchain platform enabling real-time tracking of goods from manufacturer to consumer.',
      detailedDescription: 'Each product gets an immutable digital passport recorded on-chain at every step of its journey. Consumers can scan a QR code to verify authenticity, origin, and environmental impact.',
      category        : 'Tech',
      tags            : ['Blockchain', 'Supply Chain', 'Transparency'],
      imageURL        : '',
      authorName      : 'Marcus Reid',
      authorPhoto     : '',
      authorEmail     : 'marcus@example.com',
      commentCount    : 18,
      bookmarkCount   : 8,
      estimatedBudget : '$120,000',
      targetAudience  : 'Mid-to-large retailers and ethical consumer brands.',
      problemStatement: 'Supply chain fraud costs global businesses $600B annually. Consumers cannot verify ethical sourcing claims.',
      proposedSolution: 'An enterprise SaaS platform with IoT sensor integration, smart contracts for automatic payments, and a consumer-facing verification app.',
      createdAt       : '2024-01-20T14:00:00Z',
      updatedAt       : '2024-01-20T14:00:00Z',
    },
    {
      _id             : '3',
      title           : 'Personalized Learning Path Generator',
      shortDescription: 'An AI-driven platform analyzing your skills and goals to build a custom curriculum from resources across the internet.',
      detailedDescription: 'Using skill-gap analysis and learning-style assessment, the platform curates content from YouTube, Coursera, GitHub, and books into a cohesive roadmap. Progress is tracked and the path adapts weekly.',
      category        : 'Education',
      tags            : ['AI', 'EdTech', 'Personalization'],
      imageURL        : '',
      authorName      : 'Priya Sharma',
      authorPhoto     : '',
      authorEmail     : 'priya@example.com',
      commentCount    : 31,
      bookmarkCount   : 20,
      estimatedBudget : '$45,000',
      targetAudience  : 'Self-taught developers, career switchers, and lifelong learners.',
      problemStatement: 'The internet has unlimited learning resources but no personalized structure. Learners waste months on wrong content.',
      proposedSolution: 'An AI coach that interviews the user, maps their current skills, and generates a week-by-week learning plan with curated resources.',
      createdAt       : '2024-01-22T09:00:00Z',
      updatedAt       : '2024-01-22T09:00:00Z',
    },
    {
      _id             : '4',
      title           : 'Carbon Footprint Marketplace',
      shortDescription: 'A platform where individuals and companies can trade verified carbon credits and fund certified green projects.',
      detailedDescription: 'Individuals calculate their monthly footprint via an intuitive questionnaire. They can then offset by purchasing credits from verified reforestation, solar, and methane capture projects.',
      category        : 'Sustainability',
      tags            : ['Carbon Credits', 'Climate', 'Marketplace'],
      imageURL        : '',
      authorName      : 'Tom Bradley',
      authorPhoto     : '',
      authorEmail     : 'tom@example.com',
      commentCount    : 15,
      bookmarkCount   : 6,
      estimatedBudget : '$200,000',
      targetAudience  : 'ESG-conscious enterprises and environmentally aware individuals.',
      problemStatement: 'Carbon offset markets are opaque, expensive, and inaccessible to individuals and small businesses.',
      proposedSolution: 'A transparent B2C2B marketplace with third-party audited projects, real-time impact dashboards, and API integrations for enterprise.',
      createdAt       : '2024-01-25T11:00:00Z',
      updatedAt       : '2024-01-25T11:00:00Z',
    },
    {
      _id             : '5',
      title           : 'Micro-Investment Platform for Gen Z',
      shortDescription: 'A gamified investing app letting Gen Z invest spare change into diversified portfolios with social discovery features.',
      detailedDescription: 'Round-up spare change from daily purchases and invest automatically. Leaderboards, streaks, and social feeds let users share portfolios and celebrate milestones.',
      category        : 'Finance',
      tags            : ['Finance', 'Gen Z', 'Investing', 'Gamification'],
      imageURL        : '',
      authorName      : 'Alex Johnson',
      authorPhoto     : '',
      authorEmail     : 'alex@example.com',
      commentCount    : 42,
      bookmarkCount   : 25,
      estimatedBudget : '$300,000',
      targetAudience  : 'Gen Z aged 18–26 who are curious about investing but intimidated by traditional platforms.',
      problemStatement: 'Traditional investing platforms are intimidating for young adults. 73% of Gen Z report feeling financially anxious about the future.',
      proposedSolution: 'A mobile-first platform with sub-$1 micro-investing, educational quests, and a social layer where users learn from peers.',
      createdAt       : '2024-01-28T16:00:00Z',
      updatedAt       : '2024-01-28T16:00:00Z',
    },
    {
      _id             : '6',
      title           : 'Local Food Rescue Network',
      shortDescription: 'A community platform connecting restaurants with surplus food to local charities and food-insecure families in real time.',
      detailedDescription: 'Restaurants post surplus food listings 2 hours before closing. Nearby volunteers and NGOs claim batches via the app and coordinate pickup within 30 minutes to prevent spoilage.',
      category        : 'Social Impact',
      tags            : ['Food Waste', 'Community', 'NGO'],
      imageURL        : '',
      authorName      : 'Elena Vasquez',
      authorPhoto     : '',
      authorEmail     : 'elena@example.com',
      commentCount    : 19,
      bookmarkCount   : 11,
      estimatedBudget : '$30,000',
      targetAudience  : 'Restaurants, grocery chains, and local food banks in urban areas.',
      problemStatement: '40% of food produced in the US is wasted annually while 34 million Americans face food insecurity.',
      proposedSolution: 'A two-sided marketplace mobile app with real-time notifications, route optimization for volunteers, and impact tracking dashboards.',
      createdAt       : '2024-02-01T08:00:00Z',
      updatedAt       : '2024-02-01T08:00:00Z',
    },
    {
      _id             : '7',
      title           : 'Remote Work Culture Platform',
      shortDescription: 'A virtual office platform that rebuilds team culture, spontaneous collaboration, and social bonds for distributed teams.',
      category        : 'Tech',
      tags            : ['Remote Work', 'Team Culture', 'SaaS'],
      imageURL        : '',
      authorName      : 'James Liu',
      authorPhoto     : '',
      authorEmail     : 'james@example.com',
      commentCount    : 11,
      bookmarkCount   : 7,
      estimatedBudget : '$150,000',
      targetAudience  : 'Remote-first tech companies with 20–200 employees.',
      problemStatement: 'Remote teams suffer from isolation, weak culture, and reduced spontaneous collaboration, hurting retention and morale.',
      proposedSolution: 'Virtual water cooler moments, async video conversations, culture health scores, and team-bonding activity automation.',
      createdAt       : '2024-02-05T13:00:00Z',
      updatedAt       : '2024-02-05T13:00:00Z',
      shortDescription: 'A virtual office platform that rebuilds team culture and spontaneous collaboration for distributed remote teams.',
      detailedDescription: 'Virtual rooms simulate office serendipity. AI schedules cross-team coffee chats, tracks culture health, and surfaces disengaged employees before they quit.',
    },
    {
      _id             : '8',
      title           : 'AI Legal Document Simplifier',
      shortDescription: 'An AI tool that translates complex legal documents into plain English, highlighting risks and obligations for non-lawyers.',
      category        : 'AI',
      tags            : ['LegalTech', 'AI', 'SaaS'],
      imageURL        : '',
      authorName      : 'Nina Okafor',
      authorPhoto     : '',
      authorEmail     : 'nina@example.com',
      commentCount    : 27,
      bookmarkCount   : 14,
      estimatedBudget : '$60,000',
      targetAudience  : 'Freelancers, startup founders, and small business owners signing contracts.',
      problemStatement: 'Legal fees average $300/hr. Most people sign contracts without fully understanding terms, leading to costly disputes.',
      proposedSolution: 'Upload any contract and receive a plain-English summary, risk heatmap, and negotiation tips within 60 seconds.',
      createdAt       : '2024-02-08T10:30:00Z',
      updatedAt       : '2024-02-08T10:30:00Z',
      detailedDescription: 'GPT-4 powered analysis extracts key clauses, identifies unusual terms, compares with industry-standard contracts, and generates a negotiation brief.',
    },
    {
      _id             : '9',
      title           : 'Neighborhood Skill Exchange',
      shortDescription: 'A hyperlocal platform where neighbors trade skills and services without money — a modern barter economy.',
      category        : 'Social Impact',
      tags            : ['Community', 'Sharing Economy', 'Local'],
      imageURL        : '',
      authorName      : 'Carlos Mendez',
      authorPhoto     : '',
      authorEmail     : 'carlos@example.com',
      commentCount    : 9,
      bookmarkCount   : 5,
      estimatedBudget : '$25,000',
      targetAudience  : 'Community-oriented residents in suburbs and mid-size cities.',
      problemStatement: 'Neighbors live meters apart but never interact. Local skills go unused while people pay for services they could exchange.',
      proposedSolution: 'A trust-scored skill marketplace where you earn time credits by offering skills and spend them on services from neighbors.',
      createdAt       : '2024-02-10T15:00:00Z',
      updatedAt       : '2024-02-10T15:00:00Z',
      detailedDescription: 'Verified identity, neighborhood-scoped discovery, time-banking credits, and community reputation scores create a trusted local exchange network.',
    },
  ]
  
  export const MOCK_COMMENTS = [
    {
      _id        : 'c1',
      text       : 'This is genuinely one of the most needed solutions on this platform. Mental health support should be accessible to everyone regardless of income bracket.',
      authorName : 'Alex Johnson',
      authorEmail: 'alex@example.com',
      authorPhoto: '',
      createdAt  : '2024-01-16T12:00:00Z',
      isOwn      : true,
    },
    {
      _id        : 'c2',
      text       : 'Have you considered the regulatory challenges? In many countries, AI therapy tools face strict FDA/CE oversight. Worth mapping those out early before raising a seed round.',
      authorName : 'Marcus Reid',
      authorEmail: 'marcus@example.com',
      authorPhoto: '',
      createdAt  : '2024-01-17T09:30:00Z',
      isOwn      : false,
    },
    {
      _id        : 'c3',
      text       : 'The market timing is perfect. BetterHelp is worth $1B+ and still has massive waitlists. An AI-first approach could serve 100x more users at 1/10th the cost.',
      authorName : 'Priya Sharma',
      authorEmail: 'priya@example.com',
      authorPhoto: '',
      createdAt  : '2024-01-18T15:45:00Z',
      isOwn      : false,
    },
    {
      _id        : 'c4',
      text       : 'I would love to see how the escalation to human therapists would work. That handoff is critical and could be a key differentiator if done right.',
      authorName : 'Elena Vasquez',
      authorEmail: 'elena@example.com',
      authorPhoto: '',
      createdAt  : '2024-01-19T11:00:00Z',
      isOwn      : false,
    },
  ]
  
  export const MOCK_MY_INTERACTIONS = [
    {
      _id         : 'i1',
      ideaId      : '1',
      ideaTitle   : 'AI-Powered Mental Health Companion',
      ideaCategory: 'Health',
      text        : 'This is genuinely one of the most needed solutions on this platform. Mental health support should be accessible to everyone regardless of income bracket.',
      createdAt   : '2024-01-16T12:00:00Z',
    },
    {
      _id         : 'i2',
      ideaId      : '3',
      ideaTitle   : 'Personalized Learning Path Generator',
      ideaCategory: 'Education',
      text        : 'I have been using something similar for my team and the productivity gains are real. The personalization angle is what sets it apart.',
      createdAt   : '2024-01-23T14:20:00Z',
    },
    {
      _id         : 'i3',
      ideaId      : '5',
      ideaTitle   : 'Micro-Investment Platform for Gen Z',
      ideaCategory: 'Finance',
      text        : 'The gamification angle is exactly what this demographic needs. Acorns proved the concept — adding a social layer could be the unlock.',
      createdAt   : '2024-01-29T10:00:00Z',
    },
    {
      _id         : 'i4',
      ideaId      : '8',
      ideaTitle   : 'AI Legal Document Simplifier',
      ideaCategory: 'AI',
      text        : 'This would have saved me thousands in legal fees last year. The freelancer market alone is massive — 59 million in the US.',
      createdAt   : '2024-02-09T08:45:00Z',
    },
  ]